## **Задание на повторение материала
1.	Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np

In [30]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2.	Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [9]:
b = a.reshape(4,3)
print(b)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [11]:
b = a.reshape(3,4)
print(b)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
b = a.reshape(6,2)
print(b)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [15]:
b = a.reshape(12,1)
print(b)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [16]:
b = a.reshape(2,6)
print(b)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


3.	Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
b = a.reshape(2,-1)
print(b)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [18]:
b = a.reshape(3,-1)
print(b)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
b = a.reshape(6,-1)
print(b)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [31]:
b = a.reshape(-1,6)
print(b)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [32]:
b = a.reshape(-1,1)
print(b)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4.	Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#### Ответ: нет, это двумерный массив

In [33]:
b.ndim

2

5.	Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [35]:
c = np.random.randn(3, 4)
print(c)

[[ 0.2651002  -0.14416847 -0.48669683 -0.01739089]
 [-0.38246632  1.10418261 -0.38120389 -1.40197449]
 [ 0.16562446  0.88865868 -0.87921931 -0.04461099]]


In [36]:
c.size

12

In [37]:
d = c.flatten()
print(d)

[ 0.2651002  -0.14416847 -0.48669683 -0.01739089 -0.38246632  1.10418261
 -0.38120389 -1.40197449  0.16562446  0.88865868 -0.87921931 -0.04461099]


6.	Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [42]:
a1 = np.arange(20, 0, -2)
print(a1)

[20 18 16 14 12 10  8  6  4  2]


7.	Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [43]:
b1 = np.arange(20, 1, -2)
print(b1)

[20 18 16 14 12 10  8  6  4  2]


#### Ответ: между а и b нет разницы, они одинаковы

8.	Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк 
которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 
Итоговый массив v должен иметь атрибут size, равный 10.

In [48]:
a2 = np.zeros((2, 2))
b2 = np.ones((3, 2))

In [49]:
v = np.vstack((a2, b2))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
v.size

10

9.	Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [54]:
a3 = np.arange(0, 12)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [57]:
A = a3.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [60]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [61]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [62]:
d = np.linalg.det(B)

print(d)

0.0


#### Ответ:  Матрица В имеет размер 4х4. Обратную матрицу для матрицы В вычислить нельзяб т.к. ее можно посчитать только для матрицы, определитель которой не равен  0. При попытке вычисления получим ошибку: 

In [65]:
B_inv = np.linalg.inv(B)

print(B_inv)

LinAlgError: Singular matrix

10.	 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [69]:
np.random.seed(42)

11.	Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [74]:
c3 = np.random.randint(0, 16, 16)
print(c3)

[ 7  7  2  5  4  1  7 11 13  5  1 15 11  4  0 11]


In [75]:
c3.ndim

1

12.	Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [76]:
C = c3.reshape(4,4)
C

array([[ 7,  7,  2,  5],
       [ 4,  1,  7, 11],
       [13,  5,  1, 15],
       [11,  4,  0, 11]])

In [79]:
D = B + C*10
D

array([[ 75,  84,  43,  82],
       [ 54,  60, 156, 232],
       [153, 136, 159, 362],
       [142, 162, 212, 412]])

In [81]:
d3 = np.linalg.det(D)

print(d3)

28164800.000000015


In [82]:
r = np.linalg.matrix_rank(D)

print(r)

4


In [83]:
D_inv = np.linalg.inv(D)

print(D_inv)

[[ 0.01585241  0.0205732   0.02809464 -0.0394251 ]
 [ 0.00476765 -0.0189783  -0.02534369  0.03200591]
 [ 0.01530279  0.02571011 -0.00169147 -0.01603704]
 [-0.01521261 -0.01285789  0.0011525   0.01168267]]


In [85]:
print(D.dot(D_inv))

[[ 1.00000000e+00  0.00000000e+00 -7.35522754e-16  0.00000000e+00]
 [-4.44089210e-16  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


13.	Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [86]:
D_inv = np.where (D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 1]])

In [90]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [91]:
print(C)

[[ 7  7  2  5]
 [ 4  1  7 11]
 [13  5  1 15]
 [11  4  0 11]]


In [88]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14  23   5]
 [ 14   1   7 122]
 [ 23  86   1  15]
 [ 11   4 212 302]]
